version: 2.1
orbs:
  cypress: cypress-io/cypress@1

jobs:
  jest:
    working_directory: ~/aeons-end-randomizer
    docker:
      - image: circleci/node:11.10.1
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: yarn test:jest:ci

workflows:
  version: 2
  test:
    jobs:
      - jest
      - cypress/run:
          yarn: true
          start: yarn start
          wait-on: 'http://localhost:3000'
