import * as types from 'aer-types/types'

export const expedition1: types.Expedition = {
  id: 'Expedition1',
  name: 'test',
  score: 4,
  seed: {
    seed: 'Expedition1',
    supplyState: true,
    nemesisState: true,
  },
  settingsSnapshot: {
    supplySetup: {
      id: 'random',
      name: 'Random Setup (Default)',
      type: 'official',
      default: true,
      active: true,
      tiles: [
        {
          type: 'Gem',
          operation: 'ANY',
        },
        {
          type: 'Gem',
          operation: 'ANY',
        },
        {
          type: 'Gem',
          operation: 'ANY',
        },
        {
          type: 'Relic',
          operation: 'ANY',
        },
        {
          type: 'Relic',
          operation: 'ANY',
        },
        {
          type: 'Spell',
          operation: 'ANY',
        },
        {
          type: 'Spell',
          operation: 'ANY',
        },
        {
          type: 'Spell',
          operation: 'ANY',
        },
        {
          type: 'Spell',
          operation: 'ANY',
        },
      ],
    },
    availableCardIds: [
      'DiamondCluster',
      'ChaosArc',
      'Ignite',
      'EssenceTheft',
      'SearingRuby',
      'FeralLightning',
      'PlanarInsight',
      'SpectralEcho',
      'BurningOpal',
      'ConsumingVoid',
      'UnstablePrism',
      'CloudedSapphire',
      'MagesTalisman',
      'FlexingDagger',
      'LavaTendril',
      'BottledVortex',
      'ArcaneNexus',
      'DarkFire',
      'PhoenixFlame',
      'Jade',
      'AmplifyVision',
      'VriswoodAmber',
      'BlastingStaff',
      'SiftersPearl',
      'WildfireWhip',
      'FocusingOrb',
      'OblivionSwell',
      'TripliteCore',
      'NerveJab',
      'DoubleTap',
      'ObliviumResin',
      'Summonite',
      'ManifoldContainer',
      'DrainingTouch',
      'JoltingCrust',
      'MentiteChunk',
      'SoulCords',
      'VoidiumSpike',
      'PrecisionShot',
      'MutedLacosite',
      'BladeOfWisdom',
      'StunningForce',
      'FlashOfIntellect',
      'ScholarsOpus',
      'BottledStar',
      'BurningCurrent',
      'PsychicEruption',
      'LivingGauntlet',
      'ShiningTetrite',
      'VoidBond',
      'Combustion',
      'VimDynamo',
      'DisintegratingScythe',
      'MonstrousInferno',
      'DevouringShadow',
      'BanishingTopaz',
      'Transmogrifier',
      'JeweledBrain',
      'BlastSphere',
      'WoundMender',
      'LurkingSionite',
      'UnrefinedBlaststone',
      'Exogranite',
      'RecurringJasper',
      'EnergizedRubidium',
      'ResonantPearl',
      'CagedFire',
      'GalvanizedBauble',
      'AetherConduit',
      'WellOfEnergy',
      'PainConduit',
      'LinkConduit',
      'MarbleGalaxy',
      'DelugeOfPower',
      'ReverberatingShock',
      'FatalHarmony',
      'BouncingBoom',
      'SpiritLift',
      'Tethered Darts',
      'ForceAmplifier',
      'ImbuedSmash',
      'PatternStrike',
      'MoltenHammer',
      'Radiance',
      'Blaze',
      'ScryingBolt',
      'SagesBrand',
      'LeechingAgate',
      'TemporalHelix',
      'Char',
      'AlienElement',
      'Scorch',
      'Pyromancy',
      'FeedbackAura',
      'Catalyst',
      'PainStone',
      'AstralCube',
      'RiddleSphere',
      'NetherConduit',
      'HauntedBerylite',
      'Olivinite',
      'CacheGlass',
      'ReflectiveConduit',
      'WillWeaver',
      'BreachSeeker',
      'CrescendoRay',
      'StormVapors',
      'MantraOfStrength',
      'EmbodyFlame',
      'SnapRitual',
      'ShiningFluorite',
      'PolyphaseTurbine',
      'BreachExtractor',
      'FocusingConduit',
      'DualFlash',
      'DustCaller',
      'SymbioticSynapse',
      'FossilizedScarab',
      'ThermalDart',
      'Resonate',
      'Conflagration',
      'DimensionalKey',
      'InnerFire',
      'Fulminate',
      'EternityCharm',
      'ErraticIngot',
      'ReduceToAsh',
      'VortexGauntlet',
      'Carbonize',
      'Equilibrium',
      'VolcanicGlass',
      'ConvectionField',
      'JaggedLightning',
      'BloodstoneJewel',
      'Kindle',
      'ThoughtformFamiliar',
      'Crystallize',
      'FieryTorrent',
      'CelestialSpire',
      'ConjureTheLost',
      'NovaForge',
      'DreadDiamond',
      'CairnCompass',
      'ScoriaSlag',
      'BreachOre',
      'FiendCatcher',
      'PyrotechnicSurge',
      'Aurora',
      'ConclaveScroll',
      'PrimordialFetish',
      'FrozenMagmite',
      'MagesTotem',
      'DrownInFlames',
      'FleetingVision',
      'SplinterMissile',
      'EchoStone',
      'ThievingSpirit',
      'FracturedQuartz',
      'RockLauncher',
      'AbacusOfIgnition',
      'IlluminatingFlame',
      'ChronalArc',
    ],
    availableMageIds: [
      'Adelheim',
      'Brama',
      'Jian',
      'Kadir',
      'Lash',
      'Mist',
      'Phaedraxa',
      'Xaxos',
      'Nym',
      'Reeve',
      'Zhana',
      'Inco',
      'Razra',
      'Sahala',
      'Gygar',
      'Soskel',
      'Taqren',
      'Talix',
      'Rhia',
      'Claudia',
      'Lost',
      'Malastar',
      'Indira',
      'Remnant',
      'Nook',
      'Mazra',
      'Qu',
      'Sparrow',
      'XaxosTV',
      'Dezmodia',
      'Garu',
      'Gex',
      'Mazahaedron',
      'MistWE',
      'Quilius',
      'Ulgimor',
      'YanMagda',
    ],
    availableNemesisIds: [
      'CarapaceQueen',
      'CrookedMask',
      'PrinceOfGluttons',
      'Rageborne',
      'HordeCrone',
      'Necroswarm',
      'Maggoth',
      'Arachnos',
      'AgelessWalker',
      'Fenrix',
      'BlightLord',
      'WaywardOne',
      'ThriceDeadProphet',
      'Wraithmonger',
      'TheWailing',
      'TheWanderer',
      'KnightOfShackles',
      'MaidenOfThorns',
      'GateWitch',
      'HollowCrown',
      'MagusOfCloaks',
      'UmbraTitan',
    ],
    availableTreasureIds: [
      'DezmodiasOblivionShard',
      'UlgimorsCoalFragment',
      'IndirasLoneOpal',
      'MistsAmethystParagon',
      'MalastarsImmolate',
      'YanMagdasIlluminate',
      'EyeOfTheMaelstrom',
      'WellOfDespair',
      'CronesAmulet',
      'EdibleFungusChunks',
      'UmbralHornOfWar',
      'TheBrokenMask',
      'AlchemistsAlembic',
      'SoothsayersPouch',
      'SuppressingPin',
      'Quicksilver',
      'BandOfRetrieval',
      'PurifiedBangle',
      'KadirsEmeraldShard',
      'GexsShatteredGeode',
      'JiansMoonstoneShard',
      'LashsQuartzShard',
      'XaxosFlare',
      'AdelheimsAmethystShard',
      'BramasBuriedLight',
      'GarusTorch',
      'XaxosPyre',
      'MistsGarnetShard',
      'ShimmeringCloakOfTheMagus',
      'ImbuedShackles',
      'GluttonsTooth',
      'CoreOfRage',
      'CleansingAmulet',
      'CarapaceFragement',
      'ThornedWhip',
      'BonesOfDeathmind',
      'AcceleratingGauntlets',
      'EssenceExtractor',
      'BroochOfAttunment',
      'BladedCrystal',
      'PrismOfDestruction',
      'ForgottenTrinket',
      'PrecisionMagnifier',
      'ShroudOfObfucation',
      'VerdantStaff',
      'FlowingMantle',
      'MazahaedronsWorldheartShard',
      'PhaedraxasTourmalineShard',
      'FracturedShell',
      'Extra-DimensionalLens',
      'SeersBracer',
      'RemnantsVoidShard',
      'QuiliussErasure',
      'ZhanasFleetingEmber',
      'BlightedRootClump',
      'PetrifiedWitchFinger',
      'WaywardScraps',
      'TrueSightMonocle',
      'EntwinedAetherStrands',
      'SiphoningBlade',
      'GemEncrustedAnklet',
      'ReevesRavenShard',
      'NymsVision',
      'SparrowsAid',
      'WraithsEssence',
      'VolatileClasp',
      'BreachStabilizer',
      'FangedChoker',
      'EndlessBandolier',
    ],
    availableUpgradedBasicNemesisCardIds: [
      'HissingAcid',
      'Wreck',
      'BaneCommander',
      'SkyTremor',
      'EngulfingMadness',
      'Separate',
      'NeedleDoom',
      'Marked',
      'Eradicate',
      'FlashOfDecay',
      'Terrify',
      'RayOfDesolation',
      'ThunderousTempest',
      'Sacrifice',
      'Burialskulk',
      'Rupture',
      'FurrowOfDestruction',
      'Mangle',
      'HowlingSlayer',
    ],
    usedExpansions: [
      'AE',
      'BS',
      'Depths',
      'IW',
      'NA',
      'Nameless',
      'OD',
      'SD',
      'TA',
      'TV',
      'WE',
      'promos',
    ],
  },
  barracks: {
    mageIds: ['Qu', 'Mazra', 'Nook', 'Sparrow', 'Gygar'],
    supplyIds: [
      'DiamondCluster',
      'PainConduit',
      'UnstablePrism',
      'TemporalHelix',
      'ThoughtformFamiliar',
      'BurningCurrent',
      'StormVapors',
      'CrescendoRay',
      'Aurora',
    ],
    treasureIds: [
      'SparrowsAid',
      'MistsAmethystParagon',
      'BramasBuriedLight',
      'XaxosPyre',
      'IndirasLoneOpal',
    ],
  },
  upgradedBasicNemesisCards: [],
  banished: ['SearingRuby', 'RecurringJasper', 'PainStone'],
  bigPocketVariant: false,
  sequence: {
    firstBranchId: 'CvghslX3mK',
    branches: {
      CvghslX3mK: {
        id: 'CvghslX3mK',
        nextBranchId: 'YBsJLx4PfV',
        type: 'battle',
        expeditionId: 'Expedition1',
        nemesisId: 'KnightOfShackles',
        config: {
          tier: 1,
          newUBNCards: {
            type: 'regular',
            addRandom: false,
          },
          treasure: {
            level: 1,
            hasTreasure: true,
          },
        },
        status: 'finished',
        tries: 2,
        rewards: {
          mages: [],
          treasure: [
            'SparrowsAid',
            'MistsAmethystParagon',
            'BramasBuriedLight',
            'XaxosPyre',
            'IndirasLoneOpal',
          ],
          supplyIds: ['DiamondCluster', 'PainConduit', 'ThoughtformFamiliar'],
        },
      },
      YBsJLx4PfV: {
        id: 'YBsJLx4PfV',
        nextBranchId: '0t22iBGUff',
        type: 'battle',
        expeditionId: 'Expedition1',
        config: {
          tier: 2,
          newUBNCards: {
            type: 'regular',
            addRandom: true,
          },
          treasure: {
            level: 2,
            hasTreasure: true,
          },
        },
        status: 'unlocked',
        tries: 0,
      },
      '0t22iBGUff': {
        id: '0t22iBGUff',
        nextBranchId: 'wXBtzLO1bM',
        type: 'battle',
        expeditionId: 'Expedition1',
        config: {
          tier: 3,
          newUBNCards: {
            type: 'regular',
            addRandom: true,
          },
          treasure: {
            level: 3,
            hasTreasure: true,
          },
        },
        status: 'locked',
        tries: 0,
      },
      wXBtzLO1bM: {
        id: 'wXBtzLO1bM',
        type: 'battle',
        config: {
          tier: 4,
          newUBNCards: {
            type: 'regular',
            addRandom: true,
          },
          treasure: {
            hasTreasure: false,
          },
        },
        expeditionId: 'Expedition1',
        status: 'locked',
        tries: 0,
      },
    },
  },
  finished: false,
}

export const expedition2 = {
  id: 'Expedition2',
  name: 'test',
  score: 4,
  seed: {
    seed: 'Expedition2',
    supplyState: true,
    nemesisState: true,
  },
  barracks: {
    mageIds: ['Qu', 'Mazra', 'Nook', 'Sparrow', 'Gygar'],
    supplyIds: [
      'DiamondCluster',
      'PainConduit',
      'UnstablePrism',
      'TemporalHelix',
      'ThoughtformFamiliar',
      'BurningCurrent',
      'StormVapors',
      'CrescendoRay',
      'Aurora',
    ],
    treasureIds: [
      'SparrowsAid',
      'MistsAmethystParagon',
      'BramasBuriedLight',
      'XaxosPyre',
      'IndirasLoneOpal',
    ],
  },
  upgradedBasicNemesisCards: [],
  banished: ['SearingRuby', 'RecurringJasper', 'PainStone'],
  variantId: 'DEFAULT',
  bigPocketVariant: false,
  battles: [
    {
      id: 'CvghslX3mK',
      nemesisTier: {
        tier: 1,
        isNewTier: false,
      },
      treasure: {
        level: 1,
        hasTreasure: true,
      },
      expeditionId: 'Expedition2',
      status: 'finished',
      tries: 2,
      nemesisId: 'KnightOfShackles',
      rewards: {
        treasure: [
          'SparrowsAid',
          'MistsAmethystParagon',
          'BramasBuriedLight',
          'XaxosPyre',
          'IndirasLoneOpal',
        ],
        supplyIds: ['DiamondCluster', 'PainConduit', 'ThoughtformFamiliar'],
      },
    },
    {
      id: 'YBsJLx4PfV',
      nemesisTier: {
        tier: 2,
        isNewTier: true,
      },
      treasure: {
        level: 2,
        hasTreasure: true,
      },
      expeditionId: 'Expedition2',
      status: 'unlocked',
      tries: 0,
    },
    {
      id: '0t22iBGUff',
      nemesisTier: {
        tier: 3,
        isNewTier: true,
      },
      treasure: {
        level: 3,
        hasTreasure: true,
      },
      expeditionId: 'Expedition2',
      status: 'locked',
      tries: 0,
    },
    {
      id: 'wXBtzLO1bM',
      nemesisTier: {
        tier: 4,
        isNewTier: true,
      },
      treasure: {
        hasTreasure: false,
      },
      expeditionId: 'Expedition2',
      status: 'locked',
      tries: 0,
    },
  ],
  finished: false,
}
