import { IExpansionData } from '../types'

export const DATA: IExpansionData = {
  NA: {
    id: 'NA',
    name: 'The New Age',
    type: 'standalone',
    nemeses: [
      {
        expansion: 'NA',
        name: 'Maggoth',
        id: 'Maggoth',
      },
      {
        expansion: 'NA',
        name: 'Arachnos',
        id: 'Arachnos',
      },
      {
        expansion: 'NA',
        name: 'Ageless Walker',
        id: 'Ageless Walker',
      },
      {
        expansion: 'NA',
        name: 'Fenrix',
        id: 'Fenrix',
      },
    ],
    mages: [
      {
        expansion: 'NA',
        name: 'Sahala',
        id: 'Sahala',
      },
      {
        expansion: 'NA',
        name: 'Gygar',
        id: 'Gygar',
      },
      {
        expansion: 'NA',
        name: 'Soskel',
        id: 'Soskel',
      },
      {
        expansion: 'NA',
        name: 'Taqren',
        id: 'Taqren',
      },
      {
        expansion: 'NA',
        name: 'Talix',
        id: 'Talix',
      },
      {
        expansion: 'NA',
        name: 'Rhia',
        id: 'Rhia',
      },
      {
        expansion: 'NA',
        name: 'Claudia',
        id: 'Claudia',
      },
      {
        expansion: 'NA',
        name: 'Lost',
        id: 'Lost',
      },
    ],
    cards: [
      {
        type: 'Gem',
        expansion: 'NA',
        name: 'Lurking Sionite',
        id: 'LurkingSionite',
        cost: 3,
      },
      {
        type: 'Gem',
        expansion: 'NA',
        name: 'Unrefined Blaststone',
        id: 'UnrefinedBlaststone',
        cost: 6,
      },
      {
        type: 'Gem',
        expansion: 'NA',
        name: 'Exogranite',
        id: 'Exogranite',
        cost: 3,
      },
      {
        type: 'Gem',
        expansion: 'NA',
        name: 'Recurring Jasper',
        id: 'RecurringJasper',
        cost: 4,
      },
      {
        type: 'Gem',
        expansion: 'NA',
        name: 'Energized Rubidium',
        id: 'EnergizedRubidium',
        cost: 5,
      },
      {
        type: 'Gem',
        expansion: 'NA',
        name: 'Resonant Pearl',
        id: 'ResonantPearl',
        cost: 3,
      },
      {
        type: 'Relic',
        expansion: 'NA',
        name: 'Caged Fire',
        id: 'CagedFire',
        cost: 3,
      },
      {
        type: 'Relic',
        expansion: 'NA',
        name: 'Galvanized Bauble',
        id: 'GalvanizedBauble',
        cost: 3,
      },
      {
        type: 'Relic',
        expansion: 'NA',
        name: 'Aether Conduit',
        id: 'AetherConduit',
        cost: 4,
      },
      {
        type: 'Relic',
        expansion: 'NA',
        name: 'Well of Energy',
        id: 'WellOfEnergy',
        cost: 7,
      },
      {
        type: 'Relic',
        expansion: 'NA',
        name: 'Pain Conduit',
        id: 'PainConduit',
        cost: 3,
      },
      {
        type: 'Relic',
        expansion: 'NA',
        name: 'Link Conduit',
        id: 'LinkConduit',
        cost: 6,
      },
      {
        type: 'Relic',
        expansion: 'NA',
        name: 'Marble Galaxy',
        id: 'MarbleGalaxy',
        cost: 2,
      },
      {
        type: 'Spell',
        expansion: 'NA',
        name: 'Deluge of Power',
        id: 'DelugeOfPower',
        cost: 6,
      },
      {
        type: 'Spell',
        expansion: 'NA',
        name: 'Reverberating Shock',
        id: 'ReverberatingShock',
        cost: 4,
      },
      {
        type: 'Spell',
        expansion: 'NA',
        name: 'Fatal Harmony',
        id: 'FatalHarmony',
        cost: 5,
      },
      {
        type: 'Spell',
        expansion: 'NA',
        name: 'Bouncing Boom',
        id: 'BouncingBoom',
        cost: 6,
      },
      {
        type: 'Spell',
        expansion: 'NA',
        name: 'Spirit Lift',
        id: 'SpiritLift',
        cost: 8,
      },
      {
        type: 'Spell',
        expansion: 'NA',
        name: 'Tethered Darts',
        id: 'Tethered Darts',
        cost: 3,
      },
      {
        type: 'Spell',
        expansion: 'NA',
        name: 'Force Amplifier',
        id: 'ForceAmplifier',
        cost: 4,
      },
      {
        type: 'Spell',
        expansion: 'NA',
        name: 'Imbued Smash',
        id: 'ImbuedSmash',
        cost: 5,
      },
      {
        type: 'Spell',
        expansion: 'NA',
        name: 'Pattern Strike',
        id: 'PatternStrike',
        cost: 7,
      },
    ],
  },
  IW: {
    id: 'IW',
    name: 'Into The Wild',
    type: 'mini',
    nemeses: [
      {
        expansion: 'IW',
        name: 'Necroswarm',
        id: 'Necroswarm',
      },
    ],
    mages: [
      {
        expansion: 'IW',
        name: 'Inco',
        id: 'Inco',
      },
      {
        expansion: 'IW',
        name: 'Razra',
        id: 'Razra',
      },
    ],
    cards: [
      {
        type: 'Gem',
        expansion: 'IW',
        name: 'Jeweled Brain',
        id: 'JeweledBrain',
        cost: 3,
      },
      {
        type: 'Relic',
        expansion: 'IW',
        name: 'Blast Sphere',
        id: 'BlastSphere',
        cost: 8,
      },
      {
        type: 'Spell',
        expansion: 'IW',
        name: 'Wound Mender',
        id: 'WoundMender',
        cost: 8,
      },
    ],
  },
  SD: {
    id: 'SE',
    name: 'Shattered Dreams',
    type: 'mini',
    nemeses: [
      {
        expansion: 'SD',
        name: 'The Wailing',
        id: 'The Wailing',
      },
    ],
    mages: [
      {
        expansion: 'SD',
        name: 'Nook',
        id: 'Nook',
      },
    ],
    cards: [
      {
        type: 'Gem',
        expansion: 'SD',
        name: 'Olivinite',
        id: 'Olivinite',
        cost: 3,
      },
      {
        type: 'Gem',
        expansion: 'SD',
        name: 'Cache Glass',
        id: 'CacheGlass',
        cost: 4,
      },
      {
        type: 'Relic',
        expansion: 'SD',
        name: 'Reflective Conduit',
        id: 'ReflectiveConduit',
        cost: 3,
      },
      {
        type: 'Relic',
        expansion: 'SD',
        name: 'Will Weaver',
        id: 'WillWeaver',
        cost: 7,
      },
      {
        type: 'Spell',
        expansion: 'SD',
        name: 'Breach Seeker',
        id: 'BreachSeeker',
        cost: 5,
      },
      {
        type: 'Spell',
        expansion: 'SD',
        name: 'Crescendo Ray',
        id: 'CrescendoRay',
        cost: 4,
      },
      {
        type: 'Spell',
        expansion: 'SD',
        name: 'Storm Vapors',
        id: 'StormVapors',
        cost: 4,
      },
      {
        type: 'Spell',
        expansion: 'SD',
        name: 'Mantra of Strength',
        id: 'MantraOfStrength',
        cost: 3,
      },
      {
        type: 'Spell',
        expansion: 'SD',
        name: 'Embody Flame',
        id: 'EmbodyFlame',
        cost: 7,
      },
      {
        type: 'Spell',
        expansion: 'SD',
        name: 'Snap Ritual',
        id: 'SnapRitual',
        cost: 6,
      },
    ],
  },
  TA: {
    id: 'TA',
    name: 'The Ancients',
    type: 'mini',
    nemeses: [
      {
        expansion: 'TA',
        name: 'The Wanderer',
        id: 'The Wanderer',
      },
    ],
    mages: [
      {
        expansion: 'TA',
        name: 'Mazra',
        id: 'Mazra',
      },
      {
        expansion: 'TA',
        name: 'Qu',
        id: 'Qu',
      },
    ],
    cards: [
      {
        type: 'Gem',
        expansion: 'TA',
        name: 'Shining Fluorite',
        id: 'ShiningFluorite',
        cost: 7,
      },
      {
        type: 'Relic',
        expansion: 'TA',
        name: 'Polyphase Turbine',
        id: 'PolyphaseTurbine',
        cost: 3,
      },
      {
        type: 'Relic',
        expansion: 'TA',
        name: 'Breach Extractor',
        id: 'BreachExtractor',
        cost: 5,
      },
      {
        type: 'Relic',
        expansion: 'TA',
        name: 'Focusing Conduit',
        id: 'FocusingConduit',
        cost: 5,
      },
      {
        type: 'Spell',
        expansion: 'TA',
        name: 'Dual Flash',
        id: 'DualFlash',
        cost: 3,
      },
      {
        type: 'Spell',
        expansion: 'TA',
        name: 'Dust Caller',
        id: 'DustCaller',
        cost: 5,
      },
      {
        type: 'Spell',
        expansion: 'TA',
        name: 'Symbiotic Synapse',
        id: 'SymbioticSynapse',
        cost: 7,
      },
    ],
  },
  WE: {
    id: 'WE',
    name: 'War Eternal',
    type: 'standalone',
    nemeses: [
      {
        expansion: 'WE',
        name: 'Gate Witch',
        id: 'GateWitch',
      },
      {
        expansion: 'WE',
        name: 'Hollow Crown',
        id: 'HollowCrown',
      },
      {
        expansion: 'WE',
        name: 'Magus Of Cloaks',
        id: 'MagusOfCloaks',
      },
      {
        expansion: 'WE',
        name: 'Umbra Titan',
        id: 'UmbraTitan',
      },
    ],
    mages: [
      {
        expansion: 'WE',
        name: 'Dezmodia',
        id: 'Dezmodia',
      },
      {
        expansion: 'WE',
        name: 'Garu',
        id: 'Garu',
      },
      {
        expansion: 'WE',
        name: 'Gex',
        id: 'Gex',
      },
      {
        expansion: 'WE',
        name: 'Mazahaedron',
        id: 'Mazahaedron',
      },
      {
        expansion: 'WE',
        name: 'MistWE',
        id: 'MistWE',
      },
      {
        expansion: 'WE',
        name: 'Quilius',
        id: 'Quilius',
      },
      {
        expansion: 'WE',
        name: 'Ulgimor',
        id: 'Ulgimor',
      },
      {
        expansion: 'WE',
        name: 'Yan Magda',
        id: 'YanMagda',
      },
    ],
    cards: [
      {
        type: 'Gem',
        expansion: 'WE',
        name: 'Erratic Ingot',
        id: 'ErraticIngot',
        cost: 5,
      },
      {
        type: 'Spell',
        expansion: 'WE',
        name: 'Reduce To Ash',
        id: 'ReduceToAsh',
        cost: 7,
      },
      {
        type: 'Relic',
        expansion: 'WE',
        name: 'Vortex Gauntlet',
        id: 'VortexGauntlet',
        cost: 6,
      },
      {
        type: 'Spell',
        expansion: 'WE',
        name: 'Carbonize',
        id: 'Carbonize',
        cost: 4,
      },
      {
        type: 'Spell',
        expansion: 'WE',
        name: 'Equilibrium',
        id: 'Equilibrium',
        cost: 7,
      },
      {
        type: 'Gem',
        expansion: 'WE',
        name: 'Volcanic Glass',
        id: 'VolcanicGlass',
        cost: 3,
      },
      {
        type: 'Spell',
        expansion: 'WE',
        name: 'Convection Field',
        id: 'ConvectionField',
        cost: 5,
      },
      {
        type: 'Spell',
        expansion: 'WE',
        name: 'Jagged Lightning',
        id: 'JaggedLightning',
        cost: 4,
      },
      {
        type: 'Gem',
        expansion: 'WE',
        name: 'Bloodstone Jewel',
        id: 'BloodstoneJewel',
        cost: 6,
      },
      {
        type: 'Spell',
        expansion: 'WE',
        name: 'Kindle',
        id: 'Kindle',
        cost: 4,
      },
      {
        type: 'Spell',
        expansion: 'WE',
        name: 'Thoughtform Familiar',
        id: 'ThoughtformFamiliar',
        cost: 3,
      },
      {
        type: 'Spell',
        expansion: 'WE',
        name: 'Crystallize',
        id: 'Crystallize',
        cost: 8,
      },
      {
        type: 'Spell',
        expansion: 'WE',
        name: 'Fiery Torrent',
        id: 'FieryTorrent',
        cost: 5,
      },
      {
        type: 'Spell',
        expansion: 'WE',
        name: 'Celestial Spire',
        id: 'CelestialSpire',
        cost: 5,
      },
      {
        type: 'Spell',
        expansion: 'WE',
        name: 'Conjure The Lost',
        id: 'ConjureTheLost',
        cost: 6,
      },
      {
        type: 'Spell',
        expansion: 'WE',
        name: 'Nova Forge',
        id: 'NovaForge',
        cost: 6,
      },
      {
        type: 'Gem',
        expansion: 'WE',
        name: 'Dread Diamond',
        id: 'DreadDiamond',
        cost: 3,
      },
      {
        type: 'Relic',
        expansion: 'WE',
        name: 'Cairn Compass',
        id: 'CairnCompass',
        cost: 4,
      },
      {
        type: 'Gem',
        expansion: 'WE',
        name: 'Scoria Slag',
        id: 'ScoriaSlag',
        cost: 4,
      },
      {
        type: 'Gem',
        expansion: 'WE',
        name: 'Breach Ore',
        id: 'BreachOre',
        cost: 4,
      },
      {
        type: 'Relic',
        expansion: 'WE',
        name: 'Fiend Catcher',
        id: 'FiendCatcher',
        cost: 3,
      },
      {
        type: 'Spell',
        expansion: 'WE',
        name: 'Pyrotechnic Surge',
        id: 'PyrotechnicSurge',
        cost: 4,
      },
      {
        type: 'Spell',
        expansion: 'WE',
        name: 'Aurora',
        id: 'Aurora',
        cost: 5,
      },
      {
        type: 'Relic',
        expansion: 'WE',
        name: 'Conclave Scroll',
        id: 'ConclaveScroll',
        cost: 3,
      },
      {
        type: 'Relic',
        expansion: 'WE',
        name: 'Primordial Fetish',
        id: 'PrimordialFetish',
        cost: 4,
      },
      {
        type: 'Gem',
        expansion: 'WE',
        name: 'Frozen Magmite',
        id: 'FrozenMagmite',
        cost: 3,
      },
      {
        type: 'Relic',
        expansion: 'WE',
        name: 'Mages Totem',
        id: 'MagesTotem',
        cost: 2,
      },
    ],
  },
  TV: {
    id: 'TV',
    name: 'Void',
    type: 'mini',
    nemeses: [
      {
        expansion: 'TV',
        name: 'Knight Of Shackles',
        id: 'KnightOfShackles',
      },
      {
        expansion: 'TV',
        name: 'Maiden Of Thorns',
        id: 'MaidenOfThorns',
      },
    ],
    mages: [
      {
        expansion: 'TV',
        name: 'Sparrow',
        id: 'Sparrow',
      },
      {
        expansion: 'TV',
        name: 'XaxosTV',
        id: 'XaxosTV',
      },
    ],
    cards: [
      {
        type: 'Gem',
        expansion: 'TV',
        name: 'Fossilized Scarab',
        id: 'FossilizedScarab',
        cost: 3,
      },
      {
        type: 'Spell',
        expansion: 'TV',
        name: 'Thermal Dart',
        id: 'ThermalDart',
        cost: 4,
      },
      {
        type: 'Spell',
        expansion: 'TV',
        name: 'Resonate',
        id: 'Resonate',
        cost: 6,
      },
      {
        type: 'Spell',
        expansion: 'TV',
        name: 'Conflagration',
        id: 'Conflagration',
        cost: 3,
      },
      {
        type: 'Relic',
        expansion: 'TV',
        name: 'Dimensional Key',
        id: 'DimensionalKey',
        cost: 8,
      },
      {
        type: 'Spell',
        expansion: 'TV',
        name: 'Inner Fire',
        id: 'InnerFire',
        cost: 2,
      },
      {
        type: 'Spell',
        expansion: 'TV',
        name: 'Fulminate',
        id: 'Fulminate',
        cost: 5,
      },
      {
        type: 'Relic',
        expansion: 'TV',
        name: 'Eternity Charm',
        id: 'EternityCharm',
        cost: 3,
      },
    ],
  },
  OD: {
    id: 'OD',
    name: 'Outer Dark',
    type: 'mini',
    nemeses: [
      {
        expansion: 'OD',
        name: 'Thrice Dead Prophet',
        id: 'ThriceDeadProphet',
      },
      {
        expansion: 'OD',
        name: 'Wraithmonger',
        id: 'Wraithmonger',
      },
    ],
    mages: [
      {
        expansion: 'OD',
        name: 'Indira',
        id: 'Indira',
      },
      {
        expansion: 'OD',
        name: 'Remnant',
        id: 'Remnant',
      },
    ],
    cards: [
      {
        type: 'Spell',
        expansion: 'OD',
        name: 'Char',
        id: 'Char',
        cost: 8,
      },
      {
        type: 'Gem',
        expansion: 'OD',
        name: 'Alien Element',
        id: 'AlienElement',
        cost: 4,
      },
      {
        type: 'Spell',
        expansion: 'OD',
        name: 'Scorch',
        id: 'Scorch',
        cost: 5,
      },
      {
        type: 'Spell',
        expansion: 'OD',
        name: 'Pyromancy',
        id: 'Pyromancy',
        cost: 7,
      },
      {
        type: 'Spell',
        expansion: 'OD',
        name: 'Feedback Aura',
        id: 'FeedbackAura',
        cost: 5,
      },
      {
        type: 'Spell',
        expansion: 'OD',
        name: 'Catalyst',
        id: 'Catalyst',
        cost: 6,
      },
      {
        type: 'Gem',
        expansion: 'OD',
        name: 'Pain Stone',
        id: 'PainStone',
        cost: 6,
      },
      {
        type: 'Relic',
        expansion: 'OD',
        name: 'Astral Cube',
        id: 'AstralCube',
        cost: 5,
      },
      {
        type: 'Relic',
        expansion: 'OD',
        name: 'Riddle Sphere',
        id: 'RiddleSphere',
        cost: 3,
      },
      {
        type: 'Spell',
        expansion: 'OD',
        name: 'Nether Conduit',
        id: 'NetherConduit',
        cost: 7,
      },
      {
        type: 'Gem',
        expansion: 'OD',
        name: 'Haunted Berylite',
        id: 'HauntedBerylite',
        cost: 3,
      },
    ],
  },
  Nameless: {
    id: 'Nameless',
    name: 'Nameless',
    type: 'mini',
    nemeses: [
      {
        expansion: 'Nameless',
        name: 'Blight Lord',
        id: 'BlightLord',
      },
      {
        expansion: 'Nameless',
        name: 'Wayward One',
        id: 'WaywardOne',
      },
    ],
    mages: [
      {
        expansion: 'Nameless',
        name: 'Malastar',
        id: 'Malastar',
      },
    ],
    cards: [
      {
        type: 'Relic',
        expansion: 'Nameless',
        name: 'Molten Hammer',
        id: 'MoltenHammer',
        cost: 5,
      },
      {
        type: 'Spell',
        expansion: 'Nameless',
        name: 'Radiance',
        id: 'Radiance',
        cost: 8,
      },
      {
        type: 'Spell',
        expansion: 'Nameless',
        name: 'Blaze',
        id: 'Blaze',
        cost: 4,
      },
      {
        type: 'Spell',
        expansion: 'Nameless',
        name: 'Scrying Bolt',
        id: 'ScryingBolt',
        cost: 6,
      },
      {
        type: 'Spell',
        expansion: 'Nameless',
        name: 'Sages Brand',
        id: 'SagesBrand',
        cost: 7,
      },
      {
        type: 'Gem',
        expansion: 'Nameless',
        name: 'Leeching Agate',
        id: 'LeechingAgate',
        cost: 3,
      },
      {
        type: 'Relic',
        expansion: 'Nameless',
        name: 'Temporal Helix',
        id: 'TemporalHelix',
        cost: 7,
      },
    ],
  },
  Legacy: {
    id: 'Legacy',
    name: 'Legacy',
    type: 'standalone',
    nemeses: [
      {
        expansion: 'Legacy',
        name: 'Bladius',
        id: 'Bladius',
      },
      {
        expansion: 'Legacy',
        name: 'Deathmind',
        id: 'Deathmind',
      },
      {
        expansion: 'Legacy',
        name: 'Fungal Mesh',
        id: 'FungalMesh',
      },
      {
        expansion: 'Legacy',
        name: 'Maelstrom Risen',
        id: 'MaelstromRisen',
      },
      {
        expansion: 'Legacy',
        name: 'Spawning Horror',
        id: 'SpawningHorror',
      },
      {
        expansion: 'Legacy',
        name: 'Xaxos Ascended',
        id: 'XaxosAscended',
      },
    ],
    mages: [
      {
        expansion: 'Legacy',
        name: 'Legacy Green',
        id: 'LegacyGreen',
      },
      {
        expansion: 'Legacy',
        name: 'Legacy Yellow',
        id: 'LegacyYellow',
      },
      {
        expansion: 'Legacy',
        name: 'Legacy Orange',
        id: 'LegacyOrange',
      },
      {
        expansion: 'Legacy',
        name: 'Legacy Blue',
        id: 'LegacyBlue',
      },
    ],
    cards: [
      {
        type: 'Gem',
        expansion: 'Legacy',
        name: 'Branching Radite',
        id: 'BranchingRadite',
        cost: 4,
      },
      {
        type: 'Spell',
        expansion: 'Legacy',
        name: 'Fire Chakram',
        id: 'FireChakram',
        cost: 2,
      },
      {
        type: 'Relic',
        expansion: 'Legacy',
        name: 'Brane Knife',
        id: 'BraneKnife',
        cost: 3,
      },
      {
        type: 'Gem',
        expansion: 'Legacy',
        name: 'Fulmite Slab',
        id: 'FulmiteSlab',
        cost: 6,
      },
      {
        type: 'Gem',
        expansion: 'Legacy',
        name: 'Gilded Marble',
        id: 'GildedMarble',
        cost: 6,
      },
      {
        type: 'Relic',
        expansion: 'Legacy',
        name: 'Voltaic Relay',
        id: 'VoltaicRelay',
        cost: 4,
      },
      {
        type: 'Spell',
        expansion: 'Legacy',
        name: 'Sparking Siphon',
        id: 'SparkingSiphon',
        cost: 3,
      },
      {
        type: 'Spell',
        expansion: 'Legacy',
        name: 'Breach Communion',
        id: 'BreachCommunion',
        cost: 4,
      },
      {
        type: 'Relic',
        expansion: 'Legacy',
        name: 'Infernal Mirror',
        id: 'InfernalMirror',
        cost: 5,
      },
      {
        type: 'Relic',
        expansion: 'Legacy',
        name: 'Geophage',
        id: 'Geophage',
        cost: 3,
      },
      {
        type: 'Spell',
        expansion: 'Legacy',
        name: 'Force Transfusion',
        id: 'ForceTransfusion',
        cost: 4,
      },
      {
        type: 'Gem',
        expansion: 'Legacy',
        name: 'Conductive Grit',
        id: 'ConductiveGrit',
        cost: 3,
      },
      {
        type: 'Gem',
        expansion: 'Legacy',
        name: 'Ancient Cyanolith',
        id: 'AncientCyanolith',
        cost: 3,
      },
      {
        type: 'Relic',
        expansion: 'Legacy',
        name: 'Ethereal Hand',
        id: 'EtherealHand',
        cost: 6,
      },
      {
        type: 'Spell',
        expansion: 'Legacy',
        name: 'Bending Beam',
        id: 'BendingBeam',
        cost: 5,
      },
      {
        type: 'Gem',
        expansion: 'Legacy',
        name: 'Entangled Shard',
        id: 'EntangledShard',
        cost: 4,
      },
      {
        type: 'Spell',
        expansion: 'Legacy',
        name: 'Arcane Salvo',
        id: 'ArcaneSalvo',
        cost: 5,
      },
      {
        type: 'Gem',
        expansion: 'Legacy',
        name: 'Phased Portalite',
        id: 'PhasedPortalite',
        cost: 4,
      },
      {
        type: 'Spell',
        expansion: 'Legacy',
        name: 'Pyro Geist',
        id: 'PyroGeist',
        cost: 6,
      },
      {
        type: 'Spell',
        expansion: 'Legacy',
        name: 'Breach Flare',
        id: 'BreachFlare',
        cost: 3,
      },
      {
        type: 'Spell',
        expansion: 'Legacy',
        name: 'Thunderous Oath',
        id: 'ThunderousOath',
        cost: 8,
      },
      {
        type: 'Gem',
        expansion: 'Legacy',
        name: 'Soothing Torporene',
        id: 'SoothingTorporene',
        cost: 3,
      },
      {
        type: 'Gem',
        expansion: 'Legacy',
        name: 'Arcing Silicate',
        id: 'ArcingSilicate',
        cost: 4,
      },
      {
        type: 'Spell',
        expansion: 'Legacy',
        name: 'Warping Haze',
        id: 'WarpingHaze',
        cost: 3,
      },
      {
        type: 'Spell',
        expansion: 'Legacy',
        name: 'Incinerating Fist',
        id: 'IncineratingFist',
        cost: 4,
      },
      {
        type: 'Relic',
        expansion: 'Legacy',
        name: 'Reality Stabilizer',
        id: 'RealityStabilizer',
        cost: 6,
      },
      {
        type: 'Spell',
        expansion: 'Legacy',
        name: 'Breach Collision',
        id: 'BreachCollision',
        cost: 7,
      },
      {
        type: 'Spell',
        expansion: 'Legacy',
        name: 'Fiery Conclusion',
        id: 'FieryConclusion',
        cost: 5,
      },
      {
        type: 'Spell',
        expansion: 'Legacy',
        name: 'Starfire Frenzy',
        id: 'StarfireFrenzy',
        cost: 6,
      },
      {
        type: 'Gem',
        expansion: 'Legacy',
        name: 'Crumbling Compound',
        id: 'CrumblingCompound',
        cost: 5,
      },
      {
        type: 'Relic',
        expansion: 'Legacy',
        name: 'Prophetic Lens',
        id: 'PropheticLens',
        cost: 4,
      },
      {
        type: 'Relic',
        expansion: 'Legacy',
        name: 'Adrenal Batteries',
        id: 'AdrenalBatteries',
        cost: 7,
      },
      {
        type: 'Gem',
        expansion: 'Legacy',
        name: 'Refined Lumenium',
        id: 'RefinedLumenium',
        cost: 5,
      },
      {
        type: 'Relic',
        expansion: 'Legacy',
        name: 'Void Mill',
        id: 'VoidMill',
        cost: 5,
      },
      {
        type: 'Spell',
        expansion: 'Legacy',
        name: 'Gravity Node',
        id: 'GravityNode',
        cost: 5,
      },
      {
        type: 'Relic',
        expansion: 'Legacy',
        name: 'Neural Wreath',
        id: 'NeuralWreath',
        cost: 4,
      },
      {
        type: 'Spell',
        expansion: 'Legacy',
        name: 'Sphere OfInversion',
        id: 'SphereOfInversion',
        cost: 9,
      },
    ],
  },
  Depths: {
    id: 'Depths',
    name: 'Depths',
    type: 'mini',
    nemeses: [
      {
        expansion: 'Depths',
        name: 'Horde Crone',
        id: 'HordeCrone',
      },
    ],
    mages: [
      {
        expansion: 'Depths',
        name: 'Nym',
        id: 'Nym',
      },
      {
        expansion: 'Depths',
        name: 'Reeve',
        id: 'Reeve',
      },
      {
        expansion: 'Depths',
        name: 'Zhana',
        id: 'Zhana',
      },
    ],
    cards: [
      {
        type: 'Spell',
        expansion: 'Depths',
        name: 'Void Bond',
        id: 'VoidBond',
        cost: 4,
      },
      {
        type: 'Spell',
        expansion: 'Depths',
        name: 'Combustion',
        id: 'Combustion',
        cost: 5,
      },
      {
        type: 'Relic',
        expansion: 'Depths',
        name: 'Vim Dynamo',
        id: 'VimDynamo',
        cost: 4,
      },
      {
        type: 'Spell',
        expansion: 'Depths',
        name: 'Disintegrating Scythe',
        id: 'DisintegratingScythe',
        cost: 7,
      },
      {
        type: 'Spell',
        expansion: 'Depths',
        name: 'Monstrous Inferno',
        id: 'MonstrousInferno',
        cost: 8,
      },
      {
        type: 'Spell',
        expansion: 'Depths',
        name: 'Devouring Shadow',
        id: 'DevouringShadow',
        cost: 6,
      },
      {
        type: 'Gem',
        expansion: 'Depths',
        name: 'Banishing Topaz',
        id: 'BanishingTopaz',
        cost: 5,
      },
      {
        type: 'Relic',
        expansion: 'Depths',
        name: 'Transmogrifier',
        id: 'Transmogrifier',
        cost: 4,
      },
    ],
  },
  BS: {
    id: 'BS',
    name: 'Buried Secrets',
    type: 'mini',
    nemeses: [],
    mages: [],
    cards: [
      {
        type: 'Gem',
        expansion: 'BS',
        name: 'Triplite Core',
        id: 'TripliteCore',
        cost: 4,
      },
      {
        type: 'Spell',
        expansion: 'BS',
        name: 'Nerve Jab',
        id: 'NerveJab',
        cost: 2,
      },
      {
        type: 'Spell',
        expansion: 'BS',
        name: 'Double Tap',
        id: 'DoubleTap',
        cost: 3,
      },
      {
        type: 'Gem',
        expansion: 'BS',
        name: 'Oblivium Resin',
        id: 'ObliviumResin',
        cost: 5,
      },
      {
        type: 'Gem',
        expansion: 'BS',
        name: 'Summonite',
        id: 'Summonite',
        cost: 3,
      },
      {
        type: 'Relic',
        expansion: 'BS',
        name: 'Manifold Container',
        id: 'ManifoldContainer',
        cost: 4,
      },
      {
        type: 'Spell',
        expansion: 'BS',
        name: 'Draining Touch',
        id: 'DrainingTouch',
        cost: 2,
      },
      {
        type: 'Gem',
        expansion: 'BS',
        name: 'Jolting Crust',
        id: 'JoltingCrust',
        cost: 3,
      },
      {
        type: 'Gem',
        expansion: 'BS',
        name: 'Mentite Chunk',
        id: 'MentiteChunk',
        cost: 5,
      },
      {
        type: 'Relic',
        expansion: 'BS',
        name: 'Soul Cords',
        id: 'SoulCords',
        cost: 5,
      },
      {
        type: 'Gem',
        expansion: 'BS',
        name: 'Voidium Spike',
        id: 'VoidiumSpike',
        cost: 3,
      },
      {
        type: 'Spell',
        expansion: 'BS',
        name: 'Precision Shot',
        id: 'PrecisionShot',
        cost: 3,
      },
      {
        type: 'Gem',
        expansion: 'BS',
        name: 'Muted Lacosite',
        id: 'MutedLacosite',
        cost: 5,
      },
      {
        type: 'Spell',
        expansion: 'BS',
        name: 'Blade Of Wisdom',
        id: 'BladeOfWisdom',
        cost: 6,
      },
      {
        type: 'Spell',
        expansion: 'BS',
        name: 'Stunning Force',
        id: 'StunningForce',
        cost: 5,
      },
      {
        type: 'Spell',
        expansion: 'BS',
        name: 'Flash Of Intellect',
        id: 'FlashOfIntellect',
        cost: 4,
      },
      {
        type: 'Relic',
        expansion: 'BS',
        name: 'Scholars Opus',
        id: 'ScholarsOpus',
        cost: 3,
      },
      {
        type: 'Relic',
        expansion: 'BS',
        name: 'Bottled Star',
        id: 'BottledStar',
        cost: 7,
      },
      {
        type: 'Spell',
        expansion: 'BS',
        name: 'Burning Current',
        id: 'BurningCurrent',
        cost: 3,
      },
      {
        type: 'Spell',
        expansion: 'BS',
        name: 'Psychic Eruption',
        id: 'PsychicEruption',
        cost: 8,
      },
      {
        type: 'Relic',
        expansion: 'BS',
        name: 'Living Gauntlet',
        id: 'LivingGauntlet',
        cost: 4,
      },
      {
        type: 'Gem',
        expansion: 'BS',
        name: 'Shining Tetrite',
        id: 'ShiningTetrite',
        cost: 6,
      },
    ],
  },
  AE: {
    id: 'AE',
    name: 'Aeons End',
    type: 'standalone',
    nemeses: [
      {
        expansion: 'AE',
        name: 'Carapace Queen',
        id: 'CarapaceQueen',
      },
      {
        expansion: 'AE',
        name: 'Crooked Mask',
        id: 'CrookedMask',
      },
      {
        expansion: 'AE',
        name: 'Prince Of Gluttons',
        id: 'PrinceOfGluttons',
      },
      {
        expansion: 'AE',
        name: 'Rageborne',
        id: 'RageBorne',
      },
    ],
    mages: [
      {
        expansion: 'AE',
        name: 'Adelheim',
        id: 'Adelheim',
      },
      {
        expansion: 'AE',
        name: 'Brama',
        id: 'Brama',
      },
      {
        expansion: 'AE',
        name: 'Jian',
        id: 'Jian',
      },
      {
        expansion: 'AE',
        name: 'Kadir',
        id: 'Kadir',
      },
      {
        expansion: 'AE',
        name: 'Lash',
        id: 'Lash',
      },
      {
        expansion: 'AE',
        name: 'Mist',
        id: 'Mist',
      },
      {
        expansion: 'AE',
        name: 'Phaedraxa',
        id: 'Phaedraxa',
      },
      {
        expansion: 'AE',
        name: 'Xaxos',
        id: 'Xaxos',
      },
    ],
    cards: [
      {
        type: 'Gem',
        expansion: 'AE',
        name: 'Diamond Cluster',
        id: 'DiamondCluster',
        cost: 4,
      },
      {
        type: 'Spell',
        expansion: 'AE',
        name: 'Chaos Arc',
        id: 'ChaosArc',
        cost: 6,
      },
      {
        type: 'Spell',
        expansion: 'AE',
        name: 'Ignite',
        id: 'Ignite',
        cost: 4,
      },
      {
        type: 'Spell',
        expansion: 'AE',
        name: 'Essence Theft',
        id: 'EssenceTheft',
        cost: 5,
      },
      {
        type: 'Gem',
        expansion: 'AE',
        name: 'Searing Ruby',
        id: 'SearingRuby',
        cost: 4,
      },
      {
        type: 'Spell',
        expansion: 'AE',
        name: 'Feral Lightning',
        id: 'FeralLightning',
        cost: 5,
      },
      {
        type: 'Spell',
        expansion: 'AE',
        name: 'Planar Insight',
        id: 'PlanarInsight',
        cost: 6,
      },
      {
        type: 'Spell',
        expansion: 'AE',
        name: 'Spectral Echo',
        id: 'SpectralEcho',
        cost: 3,
      },
      {
        type: 'Gem',
        expansion: 'AE',
        name: 'Burning Opal',
        id: 'BurningOpal',
        cost: 5,
      },
      {
        type: 'Spell',
        expansion: 'AE',
        name: 'Consuming Void',
        id: 'ConsumingVoid',
        cost: 7,
      },
      {
        type: 'Relic',
        expansion: 'AE',
        name: 'Unstable Prism',
        id: 'UnstablePrism',
        cost: 3,
      },
      {
        type: 'Gem',
        expansion: 'AE',
        name: 'Clouded Sapphire',
        id: 'CloudedSapphire',
        cost: 6,
      },
      {
        type: 'Relic',
        expansion: 'AE',
        name: 'Mages Talisman',
        id: 'MagesTalisman',
        cost: 5,
      },
      {
        type: 'Relic',
        expansion: 'AE',
        name: 'Flexing Dagger',
        id: 'FlexingDagger',
        cost: 2,
      },
      {
        type: 'Spell',
        expansion: 'AE',
        name: 'Lava Tendril',
        id: 'LavaTendril',
        cost: 4,
      },
      {
        type: 'Relic',
        expansion: 'AE',
        name: 'Bottled Vortex',
        id: 'BottledVortex',
        cost: 3,
      },
      {
        type: 'Spell',
        expansion: 'AE',
        name: 'Arcane Nexus',
        id: 'ArcaneNexus',
        cost: 7,
      },
      {
        type: 'Spell',
        expansion: 'AE',
        name: 'Dark Fire',
        id: 'DarkFire',
        cost: 5,
      },
      {
        type: 'Spell',
        expansion: 'AE',
        name: 'Phoenix Flame',
        id: 'PhoenixFlame',
        cost: 3,
      },
      {
        type: 'Gem',
        expansion: 'AE',
        name: 'Jade',
        id: 'Jade',
        cost: 2,
      },
      {
        type: 'Spell',
        expansion: 'AE',
        name: 'Amplify Vision',
        id: 'AmplifyVision',
        cost: 4,
      },
      {
        type: 'Gem',
        expansion: 'AE',
        name: 'Vriswood Amber',
        id: 'VriswoodAmber',
        cost: 3,
      },
      {
        type: 'Relic',
        expansion: 'AE',
        name: 'Blasting Staff',
        id: 'BlastingStaff',
        cost: 4,
      },
      {
        type: 'Gem',
        expansion: 'AE',
        name: 'Sifters Pearl',
        id: 'SiftersPearl',
        cost: 3,
      },
      {
        type: 'Spell',
        expansion: 'AE',
        name: 'Wildfire Whip',
        id: 'WildfireWhip',
        cost: 6,
      },
      {
        type: 'Relic',
        expansion: 'AE',
        name: 'Focusing Orb',
        id: 'FocusingOrb',
        cost: 4,
      },
      {
        type: 'Spell',
        expansion: 'AE',
        name: 'Oblivion Swell',
        id: 'OblivionSwell',
        cost: 5,
      },
    ],
  },
  'p-1': {
    id: 'p-1',
    name: 'Drown in Flames',
    type: 'promo',
    mages: [],
    nemeses: [],
    cards: [
      {
        type: 'Spell',
        expansion: 'p-1',
        name: 'Drown in Flames',
        id: 'DrownInFlames',
        cost: 6,
      },
    ],
  },
  'p-2': {
    id: 'p-2',
    name: 'Fleeting Vision',
    type: 'promo',
    mages: [],
    nemeses: [],
    cards: [
      {
        type: 'Spell',
        expansion: 'p-2',
        name: 'Fleeting Vision',
        id: 'FleetingVision',
        cost: 3,
      },
    ],
  },
  'p-3': {
    id: 'p-3',
    name: 'Splinter Missile',
    type: 'promo',
    mages: [],
    nemeses: [],
    cards: [
      {
        type: 'Spell',
        expansion: 'p-3',
        name: 'Splinter Missile',
        id: 'SplinterMissile',
        cost: 5,
      },
    ],
  },
  'p-4': {
    id: 'p-4',
    name: 'Echo Stone',
    type: 'promo',
    mages: [],
    nemeses: [],
    cards: [
      {
        type: 'Gem',
        expansion: 'p-4',
        name: 'Echo Stone',
        id: 'EchoStone',
        cost: 4,
      },
    ],
  },
  'p-5': {
    id: 'p-5',
    name: 'Thieving Spirit',
    type: 'promo',
    mages: [],
    nemeses: [],
    cards: [
      {
        type: 'Spell',
        expansion: 'p-5',
        name: 'Thieving Spirit',
        id: 'ThievingSpirit',
        cost: 5,
      },
    ],
  },
  'p-6': {
    id: 'p-6',
    name: 'Fractured Quartz',
    type: 'promo',
    mages: [],
    nemeses: [],
    cards: [
      {
        type: 'Gem',
        expansion: 'p-6',
        name: 'Fractured Quartz',
        id: 'FracturedQuartz',
        cost: 4,
      },
    ],
  },
  'p-7': {
    id: 'p-7',
    name: 'Rock Launcher',
    type: 'promo',
    mages: [],
    nemeses: [],
    cards: [
      {
        type: 'Relic',
        expansion: 'p-7',
        name: 'Rock Launcher',
        id: 'RockLauncher',
        cost: 3,
      },
    ],
  },
  'p-8': {
    id: 'p-8',
    name: 'Abacus of Ignition',
    type: 'promo',
    mages: [],
    nemeses: [],
    cards: [
      {
        type: 'Relic',
        expansion: 'p-8',
        name: 'Abacus of Ignition',
        id: 'AbacusOfIgnition',
        cost: 4,
      },
    ],
  },
  'p-9': {
    id: 'p-9',
    name: 'Illuminating Flame',
    type: 'promo',
    mages: [],
    nemeses: [],
    cards: [
      {
        type: 'Spell',
        expansion: 'p-9',
        name: 'Illuminating Flame',
        id: 'IlluminatingFlame',
        cost: 6,
      },
    ],
  },
  'p-10': {
    id: 'p-10',
    name: 'Chronal Arc',
    type: 'promo',
    mages: [],
    nemeses: [],
    cards: [
      {
        type: 'Spell',
        expansion: 'p-10',
        name: 'Chronal Arc',
        id: 'ChronalArc',
        cost: 7,
      },
    ],
  },
}
