on:
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types: [published]

name: Deploy release to netlify

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: netlify

    steps:
      - uses: actions/checkout@master

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      # Note: it's important that this is being run before the version is upped
      # because a commit will be created during the process
      - name: Set git config
        run: |
          # setup the username and email.
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Up version
        run: yarn version --new-version ${{ github.event.release.tag_name }}

      - name: Set remote url with github token
        run: git remote set-url origin https://${{ secrets.ACTION_GITHUB_BOT }}@github.com/on3iro/aeons-end-randomizer

      - name: Git branch
        run: git branch

      - name: Git remote
        run: git remote

      - name: Git remote url
        run: git remote get-url origin

      - name: Push version commit
        run: git push origin main

      - name: Build app
        run: yarn build

      - name: Publish app
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=build --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
