on:
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types: [published]

name: Deploy release to netlify

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: netlify

    steps:
      - uses: actions/checkout@master

      - name: Yarn
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'

      - run: yarn
      - run: yarn build

      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=build --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
