on:
  pull_request:
    branches: [main, dev]

name: Publish test build on Netlify

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Yarn
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'

      - run: yarn
      - run: yarn build

      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=build
        environment: netlify
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
